settings:
  title: 'Status Page'
  url: 'https://status.sergiozygmunt.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: teslamate-sergiozygmunt-com # unique identifier
    name: TeslaMate
    description: 'TeslaMate management console' # default=empty
    url: 'https://teslamate.sergiozygmunt.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: wordpressapo-com # unique identifier
    name: Wordpress APO
    description: 'Wordpress APO' # default=empty
    url: 'https://wordpressapo.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: sergiodemo-com # unique identifier
    name: Sergio Demo
    description: 'Sergio Demo' # default=empty
    url: 'https://sergiodemo.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: sergioforse-com # unique identifier
    name: Sergio for SE
    description: 'Sergio for SE' # default=empty
    url: 'https://sergioforse.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
 
  - id: voip-app # unique identifier
    name: VoIP App
    description: 'VoIP App' # default=empty
    url: 'https://voipsuite-lrxh.onrender.com/voip' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true   # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

